### ISSUE TITLE
Make aioredis and aiomcache soft dependencies

### ISSUE THREAD

**Issue by lixxu** [argaen/aiocache#130]
Although `aioredis` and `aiomcache` are both installed when install `aiocache`, I may never use `aiomcache` at all.

**Comment by argaen** [comment]
It's not something I've been worried about. aiomcache and aioredis are small packages and its just there in case you need Redis or Memcached instances.

I just took the decision that it was easier to install them rather than explaining in the docs what to install in case you wanted to use different backends.

I can understand this being a problem if the packages were big or difficult to install or if I integrate with more backends but for now I don't think it's a big issue.

**Comment by argaen** [comment]
Reopen if you have an example where this is really a problem for you :)

**Comment by lixxu** [comment]
if someone use `aiocache` on Windows, it's difficult to install `aioredis` which requires `hiredis`, then the problem comes.

**Comment by argaen** [comment]
Mmmm good point. I'll leave it open but it's not something I'll give priority for now

**Comment by argaen** [comment]
An approach for that: https://github.com/channelcat/sanic/blob/master/setup.py#L50

**Comment by argaen** [comment]
Branch in https://github.com/argaen/aiocache/tree/enhancement_%23130/soft_dependencies

Not as easy as thought as `cache.py` imports all backends. Need to see if possible to lazy load those dependencies.
