### ISSUE TITLE
Dog-pile effect

### ISSUE THREAD

**Issue by gjcarneiro** [argaen/aiocache#217]
This caching library doesn't handle the dog-piling effect: https://en.wikipedia.org/wiki/Cache_stampede

To do so, the set function should instead take a callback function that computes the value, instead of the value directly.  Also requires a lock.

**Comment by argaen** [comment]
Hi @gjcarneiro, you are right. It's something I have pending and want to tackle in #27. As you said this requires a lock and I have some work regarding distributed locks for redis and memcached before being able to tackle this.

My idea is to force the user to do the locking explicitly rather than passing a callback to the `set` method. This way I give more control to the user whether to lock or not. Decorators would support the param to apply the lock or not.

I'm closing this in favor of #27 because they aim for the same. Feel free to continue discussion there
