### ISSUE TITLE
Add msgpack serialization

### ISSUE THREAD

**Issue by argaen** [argaen/aiocache#362]

**Comment by ahopkins** [comment]
+1 for this!!

I stumbled across your package as I was toying around with the idea of building my own. I needed something that would integrate with my [`sanic`](http://sanic.readthedocs.io/) app, and I came across [your issue](https://github.com/channelcat/sanic/issues/47#issue-183366136).

Nice work. Glad I don't have to do it ;-)

Then, I saw you were using `pickle` and my first reaction was to point you towards [`msgpack`](https://msgpack.org/). I used it recently on [`MerkavaDB`](https://github.com/ahopkins/merkava). I think it would be a great addition here.

**Comment by argaen** [comment]
Glad it's useful :).

Using `pickle` is optional. You can always use string or json serialization if it fits. But yeah, having other alternatives would be useful for sure.

I'm out on holidays and have no experience on it. If you want to provide a MR feel free to do it :), should be a matter of adding a new serializer class

**Comment by ahopkins** [comment]
Will do. I will take a look to see what it involves. I am a bit busy myself right now with work, and I have some work I promised I would do on sanic package I maintain (https://github.com/ahopkins/sanic-jwt). Which is why I am relieved to see that you built this. Already in testing it out I dropped a 2000ms request I need to make several thousand times down to less than 1ms. Wow. Caching is a wonderful thing.

Adam Hopkins

**Comment by ahopkins** [comment]
Any chance the version that support `msgpack` will be released on pypi any time soon?

**Comment by argaen** [comment]
Yeah, will do today or tomorrow :)

**Comment by argaen** [comment]
@ahopkins new release done https://github.com/argaen/aiocache/releases/tag/0.9.0 :)
