### ISSUE TITLE
UnboundLocalError when using cached_stampede

### ISSUE THREAD

**Issue by borisnaydis** [argaen/aiocache#389]
The `@cached_stampede` decorator throws `UnboundLocalError` when a decorated function is called multiple times when cache is empty.

### Error:
```
Error handling request
Traceback (most recent call last):
  File "C:\Git\test_project\.venv\Lib\site-packages\aiohttp\web_protocol.py", line 410, in start
    resp = yield from self._request_handler(request)
  File "C:\Git\test_project\.venv\Lib\site-packages\aiohttp\web.py", line 325, in _handle
    resp = yield from handler(request)
  File "C:\Git\test_project\.venv\Lib\site-packages\aiohttp\web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "<ipython-input-1-bfa0dca86818>", line 15, in test
    await test_func(val)
  File "C:\Git\test_project\.venv\Lib\site-packages\aiocache\decorators.py", line 69, in wrapper
    return await self.decorator(f, *args, **kwargs)
  File "C:\Git\test_project\.venv\Lib\site-packages\aiocache\decorators.py", line 170, in decorator
    return result
UnboundLocalError: local variable 'result' referenced before assignment
```

### Steps to reproduce:
1. Start application
```python
import asyncio
from aiocache import cached_stampede
from aiohttp import web

@cached_stampede(ttl=5, lease=1)
async def test_func(val):
    await asyncio.sleep(5)

async def test(request):
    val = request.match_info['val']
    await test_func(val)
    return web.Response(text=f"Val is {val}")

app = web.Application()
app.router.add_get('/{val}', test)
web.run_app(app)
```

2. Go to http://localhost:8080/anything_you_like

3. Hit the F5 key fast several times.

**Comment by argaen** [comment]
Yup, was able to reproduce. Thanks for reporting!

**Comment by argaen** [comment]
Hey @borisnaydis Ive (well @pfreixes) found the cause. Basically this is happening because when hitting F5 in the same browser tab, previous request is cancelled and leads to an unexpected path which raises this unbound result exception. I take two actions from here:

- I will make this path play nicer, will raise the Cancelled Error in case this happens so instead an unbound error, we will se a cancelled error (which is expected)
- I will add a new attribute to shield the real function calls from being cancelled https://github.com/argaen/aiocache/issues/393

PS: If you this in different browser tabs or background curl queries behavior is expected, the bug is only when the task gets cancelled.
