### ISSUE TITLE
Better support for choice of endpoint for aioredis 

### ISSUE THREAD

**Issue by John-Gee** [argaen/aiocache#450]
Hello,

sorry for the delay.
As discussed in https://github.com/argaen/aiocache/issues/426#issuecomment-443124618

aiocache only seemed to allow for setting up the address and port and not the unix socket. I believe the issue is simple:

aioredis offers 3 choices from [documentation:](https://aioredis.readthedocs.io/en/latest/api_reference.html)
- a Redis URI — "redis://host:6379/0?encoding=utf-8"; "redis://:password@host:6379/0?encoding=utf-8";
- a (host, port) tuple — ('localhost', 6379);
- a unix domain socket path string — "/path/to/redis.sock".

but aiocache only supports [one option](https://github.com/argaen/aiocache/blob/06988236c91074817a25e15febfdda2eca193573/aiocache/backends/redis.py#L219):
self._pool = await aioredis.create_pool((self.endpoint, self.port), **kwargs)

I have tried removing the tuple with the port, and the unix connection worked so it should not be very difficult to fix this.

I am happy to submit a PR with the change needed to support all 3 options. The easiest way would probably be to offer exactly the same inputs as aioredis, but that would break the scheme with the other backends. Maybe we can assume that if the port is not specified or if the endpoint contains a slash, it is not the tuple option and pass the string only. Do you have a safer idea?

Thank you!

**Comment by argaen** [comment]
Hey @John-Gee thanks for opening this. Yes I've been thinking about this for a while, in the latest version of master there is this `Cache.from_url` available: https://github.com/argaen/aiocache/blob/master/aiocache/factory.py#L100

This relies on a method from each backend that can parse custom `URIs` for each backend implementation. For example the Redis one: https://github.com/argaen/aiocache/blob/master/aiocache/backends/redis.py#L255. I'm starting to think maybe it would be better if instead of just parsing the `path`, each cache could be responsible of the implementation of parsing the full `url`, then we could put this behavior you mention in that implementation...

I like this more because its more explicit than checking if there is a slash in the endpoint, what do you think? looking for a second opinion here :)

**Comment by John-Gee** [comment]
Probably because I don't have a good understanding of aiocache or aioredis, I am a bit lost here.

If you have a function that works on a URI you already know not to make a tuple out of it, so why do you need to parse the URI when, at least in redis' case, the db will accept the full string?

It should be fairly easy to see if what's passed is actually a redis scheme or simple socket path, and return the correct options object. Which does seem clean indeed.

**Comment by argaen** [comment]
> If you have a function that works on a URI you already know not to make a tuple out of it, so why do you need to parse the URI when, at least in redis' case, the db will accept the full string?

Design decisions I did in the beginning, trying to fix it now somehow :). Backends have public `endpoint` and `port` attributes so will have to parse for this in case. But yes the underlying implementation can be changed so in case of Redis we forward the URL directly instead of using a tuple.

My point being: I don't want to do breaking changes in order to fix this, but yes it should be possible to fix this in a nice way :)

**Comment by John-Gee** [comment]
Fair enough.

I've just tested and simply not passing the port is not breaking, you just default to the standard one; so checking for that parameter would not work anyway.

Where would you like to parse the endpoint and make the decision? It would work in _get_pool I believe but I'm guessing it's not the optimal place. Although it's the function where we would need to know which call to make.

**Comment by argaen** [comment]
I would support this only in the `Cache.from_url` method and leave the constructors like `RedisCache` out of the equation. Then I would implement the functionality in the method `parse_uri_path` (renaming it of course) in order to decide if what we receive is a url or a unix socket.

I'm talking about current master version.

Does that make sense to you?

**Comment by John-Gee** [comment]
Are you saying that you want the constructors to not gain the new behavior but instead have it only through Cache.from_url?

If so, that'd be very fine from my little user's point of view, but it makes your API a little weird I think.

Now at the end of Cache.from_url you currently call the constructor, that eventually will call RedisBackend._get_pool. Does your plan involve changing that function or not calling it?

**Comment by argaen** [comment]
> Are you saying that you want the constructors to not gain the new behavior but instead have it only through Cache.from_url?

yup

> but it makes your API a little weird I think.

Well.. depends on how you look at it, you have the constructors that have the same behavior as before, where you receive endpoint and port. Then you have a `from_url` method in the `Cache` factory in case you want this behavior.

I want to move usage to always use `Cache` instead of the constructors directly, it gives a single point of entry

> Now at the end of Cache.from_url you currently call the constructor, that eventually will call RedisBackend._get_pool. Does your plan involve changing that function or not calling it?

Yes I'm not 100% sure how to link that, would have to play a bit with it to get an idea. Feel free to make a proposal and we can review if you want :)

**Comment by John-Gee** [comment]
> I want to move usage to always use `Cache` instead of the constructors directly, it gives a single point of entry
> 
Oh if you're planning on getting there that's fine, it'll just be a bit weird during depreciation time.

> Yes I'm not 100% sure how to link that, would have to play a bit with it to get an idea. Feel free to make a proposal and we can review if you want :)

Well, maybe the address object needed by aioredis could be created outside of that function, and passed to it. That way that function merely passes it without getting more complicated.

Instead of
> self._pool = await aioredis.create_pool((self.endpoint, self.port), **kwargs)

You'd simply have

> self._pool = await aioredis.create_pool(self.address, **kwargs)

with address either being (self.endpoint, self.port) or the url.

I'm not sure about having a member variable with a dynamic type though, it's a bit strange. Maybe having 2 variables, and simply using the non none one makes it clearer.

If I have time tonight, I'll try to write a prototype of this. If not I'll be going on vacation next week and wouldn't be able to get to it for about the next 2 weeks. Well unless I end up bringing a laptop, which I might.

Once we get something acceptable for Redis, we could move onto the other backends. For the simple one I guess throwing an unsupported error would be enough, a dict does not need a complex URL... For memcached, the documentation of aiomcache is pretty sparse, but the code makes me think that there is no other option but the current one, so again simply not supporting this may be enough. This means that Cache.from_url would only be used for Redis, but since you made it generic, I'm probably missing something. What is it? :)

Thank you!

**Comment by argaen** [comment]
> with address either being (self.endpoint, self.port) or the url.

if we get `endpoint` and `port`, we could still create the address manually in the constructor right? This way address always has the same type

> This means that Cache.from_url would only be used for Redis, but since you made it generic, I'm probably missing something. What is it? :)

the `from_url` lets you specific any parameters, so for example if for the memory one you want to specify a namespace, you can do that providing `memory://?namespace=hello`. For memcached, you can do `memcached://endpoint:port?timeout=1`. One thing is what the underlying client supports, and the other is how we parse the input URL. We are just providing a standardised way of specifying initialisation of new instances and it happens that aioredis supports this out of the box by just forwarding the address while with the others, we still have to go with providing endpoint/port or tthe constructor args :)
